name: Build
on:
  schedule:
    - cron: "21 21 * * *"
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "silverblue-setup"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  fastfetch_builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: "builders"
          containerfiles: "builders/Dockerfile.fastfetch"
          image: fastfetch_builder
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: fastfetch_builder
          tags: "latest"
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

  eza_builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: "builders"
          containerfiles: "builders/Dockerfile.eza"
          image: eza_builder
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: eza_builder
          tags: "latest"
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

  lazygit_builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: "builders"
          containerfiles: "builders/Dockerfile.lazygit"
          image: lazygit_builder
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: lazygit_builder
          tags: "latest"
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

  build_silverblue:
    needs:
      - eza_builder
      # - zellij_builder
      - lazygit_builder
      - fastfetch_builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # Build image using Buildah action
      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: "."
          containerfiles: Dockerfile
          image: ${{ env.IMAGE_NAME }}
          build-args: |
            FEDORA_VERSION=39
            SOURCE_IMAGE=silverblue
          layers: false
          oci: true

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: "latest"
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
